language: node_js
node_js:
  - "10"
cache:
  npm: true
  directories:
    - "node_modules"
services:
  - mongodb
notifications:
  email: false
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
install:
  - npm install
  - npm install --global codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - secure: "IdLtCS2re+KHl72KUjjquseZUiWT1y25uvlULJ0hHxwSQLfwtO0/MC6p7RNPiPwCA2mkBuNflRf1LPV1fJ73+9SomeWItU0T69t1IrDVQwwisTiueeKmuykL4HQMTxBZsvoaNvtb4LVZwQeQnNLsBeEZy1eHDrcLYDnm7NV8mhWyt9rh5TaWqzkitzxMU4unEyU9L69TMVY+CRisufXF9B+yWtDf4vJ0N3a8AMQvrdIgfAW3RINV/Mej0Cnz0F0Jheg/0LhCOrg7NsfXQfFWJRbWsY+HB3xQXfTrUn88hoP6pvdqR0VA+5kmBgVntXej1hRdFXlFHyyV+6MTp8598pwW79mpIzE3uBs7dhML77Oo/HqS75kZ0h4//pLYBpBz/xtNfxCImn5AxONE+4mqhEXPOw6fGQ3HJT6X+BHeCv9fqivhlsFxdIw9F8ebZh7aC97z6eYzDUEjJRaRTTEYDWTqtwi9WtFe/kKWqBQfkmwLM6n9J1yrczEFSlkfO2bVyABP/kiAyWy/zH2S8tJFDjFr+TYxAZ1s1XAQeQrxCfbb8P1YYrcnXPecWLaVDSsw//1q3biCWKTEmH71MUOR2qT3zkRWDp/KXGILJ/+7PJvpTpsYhwc/SzCaULFezAkgPzt7lMtluVa8oBBmhGs9S2uWJDL2LazaAlx/SMDZHzs="
    - secure: "BwmHLhoNSJV0uyxPVUhooFrEgIV5sqq2Z6/MTwfp1cI9ovnkR4KvVjEy1WODig1YfZ6hfqLzs84ZDRbN4cR/e2qRv6s4nybyaMQmGz1Ssu/btB0S46J7hngaS9Yfm0e1Z5NqVHdR9jWyIY/PbMn+Akfu3D3uiZv/9Nda8nH5iIEW2C/CIzf6pmo1VSMYeW/D/qXW3hdgY2HEkTTJpBqTuLXOJIRYffW6cKTdyKtax8FcDKFFeqRU5kuCtfYiPGyBhPAfDhl+xvQzD+etpkuKyFIucHQnw9kDgymHDf6NSqrNMQo2Mi91ywVoagNJRnY8NNVRKIDUjxhO1d+daBZexN5Q3iP8H6bmDPgRhLElNv8feLXjZDO96GwiYlowBK5Vt6OMaVqA6kr1VEV5alq7LkvQw/YLyZaDBo3JhNtTSR4nxj6vwexJ3DY2KYe0oJhyrkXnt1eyVoNfKJkRd2oCeqDZbMJklI3XbPiVX8pfveCoZTefZTwp21mWtfMlHK86Ejl8nTUGim3G5gCAMJUy15f+8q+YNVMcKrEF13TEfln4F4U3GLR92VSx8qeAf4CzPBDm9P9RA+OBSVIZL33sW5+vwrOKMmriYgfvJQf/Sl/TDMB9W5IyRsBeyrcPV4m3jrI06/YvdlFQHuTHLrRRPjvpyM1s7bPLwuLiwsyvaZo="
    - secure: "rynQsapu/bn8S28YWROXcse187zg66thHs1GHJU6jks5U4oSN1SkyU7BUYuYzVvtxf1cLZU9COpoOVKu7/d3gDxuwIiAJ5GOVfB5ZmVZGXV6khaD3IoQkWi8IfM3zib6s5DVBVrdj/Hdz2k+JiPbQ3vwzcadYAvTlhpXnNHePrJtDu1EOT2fGaGscLPq7uzmHTxiB1so9EhNvJCTR95b48ovsoGaxXnsobdDGt1lNbqkQcbTZcBwGj7kwPHbaiGRnGYW6jy7XTemQ17/9MdtgbJ1R2RGib+fckU2PCnwD6CmLsSMmXBFhrYM0MblWhLQvx6lSSk1MPzzFu8B8LmKfdOm4u8iw9rqmjch3jchJENtPmJDXuWvFjFmbpmju//pvszrL/FTO03qoy+tjEUOh7z9ffDG+WHzl4no6RnjtKVaw0pJ8kmy5skHySZAUrhNGDzpRTJVDKojPpR5Zlfs2y2gNYTKxO+AYbTl1WVO/5YButGxqzcNiLsnuy1sYxUeMpEt1Ejprl5lZtINDTghkj1c1jTLTJvqoKcWf1hGqHzwNNM7QJAbyLRkE/6TSejq0iGFlgJcSf1+WYFJNPTzX2CnJpoxny8aH44eUIQhDp7tLtVzZDrZYtRSTuuyiiba7vfQEGT8WV2a/bMGL8QnD0pI0eWe3RtQcXYtqhzRdhA="
    - secure: "i3uh1vLmcAmVQGGE5EcOPvruGelNhjXH34Ye9o25ReygmFVt/UInDzypMKWlFNvpzPqEP8+FP9XVoWc3PUMvtyOpgaI29fhx9QLgXe/wsihZz7OYLThfa81cYnjYR9vKGtM+IbDoV5JHfzOiM9MYVCwYyfl+LhybMTfvOgT24lxlnHliuMmhseCCqkpSoPVgfyeWjlpTxdpkjegDtQoAvgHIp/gPIM5BNMWIg1Iszty7JxJomn2EfsJCAEXPe/HlipbldB+EJYHJMOYlvtJdipN9v1JfqB2VaZ+pyiZSljUzlwsh0aMM81zyDMJphuvzZWTYNXi//vohyfu2OSMC5vuSyev/wEGqmYPovrXB3b6a8cqICLlRqTC4d5Ga0QhqoI415eGyJ1BC+bYJnz55oxgx2yISnMWu3cXn6uC9TPDheISp0HuSjBmNLeFBM8GJkcK319OXDeJ8xmTA+6corMf0YioDZAdMhwsOA5Z9ZUqkcQCT65IO+9PRJv4Yn8wG7bL3EM4r3YHpDoKfYvf1QPWiWH5HehIGblw/lStdc3Rwz7/lhYXOw3TvApC2WhdsX0JKSpPQEuAZfI/0RpgChW+P7ESn9qxVXATwhuTBcCQdpzaQchrbtSUTkfDmKlLuq9zKG4k+RDvlFw8FJ5wXi19z8M22/yiwvt5p7tV6lMo="
